# Generated by Django 2.1.4 on 2019-05-19 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bike',
            fields=[
                ('bike_id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=10)),
                ('description', models.CharField(max_length=800)),
                ('rating', models.IntegerField(default=0)),
                ('price', models.IntegerField(default=0)),
                ('quantity', models.IntegerField(default=0)),
                ('bike_type', models.CharField(max_length=100)),
                ('cover', models.ImageField(default='images/404.jpeg', upload_to='media/images/')),
            ],
        ),
    ]
