# Generated by Django 2.1.4 on 2019-05-19 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bikes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bike',
            name='cover',
            field=models.ImageField(default='images/404.jpeg', upload_to='images/'),
        ),
    ]
